### ISSUE TITLE
CLI installation instructions

### ISSUE THREAD

**Issue by mihha** [gregordr/ImageStore#11]
Would it be possible to provide step by step instructions for CLI installation, without using docker-compose or docker at all?

Please don't just say that docker-compose can be deconstructed in CLI instructions. I am aware that someone who has experience with this could do it but for the rest of us, seasonable users, who don't want to use docker, this is somewhat difficult and I for sure wouldn't ask for this if it would be a straightforward process

Thank you in advance!

**Comment by gregordr** [comment]
Alright, I have written down some basic instructions. I personally find it harder to use it via CLI, but you do yours! Let me know if everything works out!

**Comment by mihha** [comment]
Thank you for providing CLI instructions

I will try to make them work and let you know how it goes

**Comment by roaldi** [comment]
I too dislike docker. Would me building a CLI build script be useful? Would install everything required, then create/start a service for it.

**Comment by gregordr** [comment]
That would be great, at least for the frontend, backend, database and nginx! Rough instructions are in the readme, but if you can compile them into one script, that would be amazing!

**Comment by roaldi** [comment]
Can do! I'll script one up in my fork, and do a pull request when it looks good.

**Comment by roaldi** [comment]
Do you have a targeted OS? Or I can make it for both rhel-like and debian-based.

**Comment by gregordr** [comment]
I am personally using debian, but the more options we have, the better of course!

**Comment by roaldi** [comment]
What node version?

**Comment by gregordr** [comment]
I am using 14, but 15 should work fine! I am more curious however what the plan is if the user has already installed a version of node. Won't those collide? Or can they be installed in parallel?

**Comment by roaldi** [comment]
I'll test it out, and see what happens. Either that, or just do a check for node, and skip if its there. Although I think its a fair assumption that the average person already running node would know how to deconflict that. I think.

**Comment by gregordr** [comment]
Sounds good! Thanks :)

**Comment by roaldi** [comment]
Just submitted a pull request. Per Issue #24 , I will continue working on it, create an imagestore user, and run in that context.
