### ISSUE TITLE
detectron2 error

### ISSUE THREAD

**Issue by jritsema** [gregordr/ImageStore#12]
Thanks for sharing this app!

I just tried spinning it up with detectron2 enabled and got the following error.  Haven't had a chance to look into yet, but wanted to note it here.

```
detectron2_1  | predicting
detectron2_1  | Traceback (most recent call last):
detectron2_1  |   File "/code/./app.py", line 27, in <module>
detectron2_1  |     prediction = im_clf.predict(im)
detectron2_1  |   File "/code/classification/model.py", line 49, in predict
detectron2_1  |     dataset_dict = get_image_blob(x, self._cfg.MODEL.PIXEL_MEAN)
detectron2_1  |   File "/code/bottom-up-attention.pytorch/utils/extract_utils.py", line 40, in get_image_blob
detectron2_1  |     im_orig -= pixel_means
detectron2_1  | ValueError: operands could not be broadcast together with shapes (2592,4756,4) (1,1,3) (2592,4756,4)
imagestore_detectron2_1 exited with code 1
```

**Comment by gregordr** [comment]
Interesting, thanks! Could you maybe share the image that is causing the issue?

**Comment by jritsema** [comment]
It's the one from the docker-compose.yml file

'image: imagestored/detectron2'

**Comment by gregordr** [comment]
Ah sorry, I meant the picture, I thought that maybe there is something unusual going on width it.

**Comment by gregordr** [comment]
Either way, I have made it so it at least doesn't crash!

**Comment by jritsema** [comment]
Ah, sorry I misunderstood.  I just pulled the latest docker images, started with a blank app (`docker-compose up`), uploaded this single image and got this error (different from the last one).

![john-park-square](https://user-images.githubusercontent.com/934927/106630385-cb22b700-6549-11eb-8c83-ca728978eb1b.jpg)


```
imagestore_detectron2_1 exited with code 137
```

**Comment by gregordr** [comment]
That's really odd, and shouldn't happen. You are on x86_64 I assume? Let's try to figure out what's wrong then.

First, can you maybe post the modified docker-compose file?

Second, can you confirm that your digests are the following?

```
sha256:388663a6497e5d1b8f551ad6326d9e3ec142a9cff32575e17e7d0dc3245dd844
sha256:65ffabcea423ee41c90b2f09abe57689195e8b0a1f3030cf0472ad465b0ff224
sha256:336caef02193d0ed760bea853f97c0066dbad6e699c267727ea234365ec11042
sha256:91a3a36d01ceb9b8f514f6866fdab0f116c18383b08d47cbcbcb27243555d989
sha256:388663a6497e5d1b8f551ad6326d9e3ec142a9cff32575e17e7d0dc3245dd844
```

If yes, can you try launching the same instance again, and post the entire log that you get? 

Last, as you said `started with a blank app`, did it say `backend_1     | Created Table media`, or `backend_1     | Table media exists`?

If that doesn't get us anywhere, my only other idea would be to send over the containers, so that I can inspect them.

**Comment by gregordr** [comment]
For reference, this is what I get from the image:

![image](https://user-images.githubusercontent.com/36226087/106692769-6745d000-65d5-11eb-8a4b-7f7125f3cf28.png)

**Comment by jritsema** [comment]
I tested this again with a later release and I longer receive the error.  The detection is working intermittently for me, but I'll go ahead and close this issue.
