### ISSUE TITLE
Mobile Safari Height Issues On Summary Page

### ISSUE THREAD

**Issue by KyleApfel** [gregordr/ImageStore#22]
On mobile safari (tested on iPhone X and iPad Pro, happens on both) there seems to be an error calculating the scrolling height of the page on the first attempt. Once I reach the “end” of the page for the footer or header, it stops until I swipe up again then it adds the height I need to scroll. If on the bottom of the page for a second and attempting to scroll the top, it happens to the top of the document as well. 

Attached video of the behavior on iPhone.

https://user-images.githubusercontent.com/7343948/107790750-b946ce00-6d18-11eb-8910-918051a4fe78.MP4

**Comment by gregordr** [comment]
Should hopefully be fixed now!
