### ISSUE TITLE
Add semantic versioned tags

### ISSUE THREAD

**Issue by vaskozl** [gregordr/ImageStore#23]
Currently the only available tags on dockerhub are `test` and `latest`.

This makes it hard to keep track of which version you are running (are you running the latest "latest" images) and updating, especially in a gitops environment.

Would be great to add support for semantic versioned releases based on git tags to the build pipeline.

**Comment by gregordr** [comment]
So you suggest that instead of tagging with `test `and `release`, we should tag with `test` and `v1.x`? I assume pulling `image:latest` would break then though, and instead one would have to pull just `image` or `image:v1.x` (where 1.x is the latest version) to get the newest release?

**Comment by vaskozl** [comment]
I'm suggesting we also add semvers like `v0.1.2` or `0.1.2`, where the `latest` is kept in sync with the largest ready release. So each release pushes two tags at least `:latest` and a versioned one. Most big projects will push major and medium versions. E.g. for redis there currently `6.0.10`, `6.0`, `6`, `latest` which are all the same. This is usually done with a git tag so you can also easily cross-reference changes on github.

From a user side it lets you pin the version in git (if you are deploying via GitOps) and gives one visibility of version changes. Myself and others use scripts to check for new image release and make MRs, so you can keep up deployment update while keeping it in a known state where you can revert if there was a breaking change etc. Also lets you see major version bumps where there might be braking changes. Bumping versions also makes K8S download the new image while by default `:latest` never gets rechecked following the initial pull.

Using `:latest` on the client means you either always update or never and is in general doesn't give you much info on which version you are running. Nevertheless `:latest` is useful for interactive use or testing etc.

**Comment by gregordr** [comment]
I understand! I assume there is no way to make the tags autoincrement, and I would have to manually tag versions in github?

Then, https://github.com/docker/build-push-action#handle-tags-and-labels would do the job if I add latest to the list?
