### ISSUE TITLE
Any suggestions on performance limits?

### ISSUE THREAD

**Issue by chmac** [gregordr/ImageStore#31]
Firstly, thanks for sharing this, it looks awesome!

Do you have any idea how this scales? I'm wondering if it's built to handle say 20k photos, total volume 150GB or similar?

**Comment by gregordr** [comment]
I remember trying with around 5k photos and it was fine, at least on my machine and my browser. Just uploading had to be done in steps. If you find performance issues, please lmk which browser and which version you use!
