### ISSUE TITLE
Detectron2_1 error brand new docker install

### ISSUE THREAD

**Issue by nickm324** [gregordr/ImageStore#38]
when I start the docker compose file everything starts up but the detectron2.
In the log I see a single error.

Traceback (most recent call last):

File "/code/./app.py", line 7, in <module>

from classification.model import ImageClassifier

File "/code/classification/model.py", line 18, in <module>

from utils.extract_utils import get_image_blob

File "/code/bottom-up-attention.pytorch/utils/extract_utils.py", line 3, in <module>

import cv2

File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>

from .cv2 import *

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by ev-w** [comment]
Same error here, except I'm trying to use yolo

**Comment by gregordr** [comment]
Could you try pulling the container again after https://github.com/gregordr/ImageStore/runs/2385692582 and https://github.com/gregordr/ImageStore/runs/2385692530 finish?

**Comment by nickm324** [comment]
I will try pulling the container again but I tried both yolo and detector2 and had the same issue with both.

**Comment by gregordr** [comment]
Any updates from your side?

**Comment by ev-w** [comment]
Working great for me now!
