### ISSUE TITLE
No Security Or user management?

### ISSUE THREAD

**Issue by nickm324** [gregordr/ImageStore#39]
So I take it this something you could never expose to the internet, I do not see any mechanism to prevent just anybody from deleting all your images.

Is this for internal use only?

**Comment by gregordr** [comment]
I would generally recommend to either VPN into your network, or use a gatekeeper like Traefik, Caddy or use nginx for authentication.

**Comment by nickm324** [comment]
But its not for external consumption since there is no way to prevent anyone from just deleting all the images you have added.

**Comment by gregordr** [comment]
Ah now I get the question. Yes, currently not :/ What you could try is only letting through get queries in nginx, but I'm not sure if this will work as expected.
