### ISSUE TITLE
[Feature Request] Upload photos from phone

### ISSUE THREAD

**Issue by Backslashh** [gregordr/ImageStore#52]
Would be great to have a way to upload photos taken from phones directly to ImageStore (to be sorted into year/month folders on the file system). 

Integration with apps like PhotoSync (using WebDav) or something similar might be useful

**Comment by gregordr** [comment]
Do you happen to have any dev experience? I managed to stitch together a WebDAV server which will upload all photos you move into it, but it still needs some testing, especially regarding how it works on macOS.

**Comment by Backslashh** [comment]
oh nice!
So ImageStore is running the WebDav server and will import photos from that WebDav location?
I can help test that's for sure. I have a bit of dev experience, but mainly front end HTML type stuff and PowerShell (I'm a Systems Engineer by trade)

**Comment by gregordr** [comment]
I played around with both WebDav and FTP, both aren't ideal for this tough.

WebDav seems to create issues when accessed with Windows Explorer sadly - it works fine until you try viewing around 10k files, and then gives up. FTP doesn't show any file previews in windows explorer and is a bit annoying in general, but at least it's consistent.

Here is the repo with the code I hacked together:

https://github.com/gregordr/testFTP

This will create an FTP server at ftp://localhost:21
You might need to change the used addresses in the script from :4000 to :3000/api if you use it with docker. While it's very hacky, you should at least be able to put files into the directory and copy them out of there. LMK how this goes for you!

**Comment by gregordr** [comment]
Looks like PhotoSync upload works this way btw! I'm still not happy with how FTP won't show file previews though :/

**Comment by Backslashh** [comment]
oh great. I use PhotoSync currently with PhotoPrism and it has been working well for me. What I like with PhotoPrism and WebDav is that once WebDav uploads have been triggered, PhotoPrism waits a pre-determined amount of time (180 seconds by default) and then runs an import.

I'll pull down the code today and run it in  docker to test. :-)

**Comment by gregordr** [comment]
I think if it's just about importing then both WebDAV and FTP will work just fine. I was hoping I might be able to make the images browsable as well, but that's not possible in a good way. Either way, the code I posted will upload everything in real time, should be good enough for starters.

**Comment by Backslashh** [comment]
That's great. My use case is purely for getting photos off my phone without having to use additional services like minio, or NextCloud. Having an integrated solution that will display/organise my photos and upload them is a huge win for me.

Will ImageStore ever organise images/videos? As in, organise them on the file system - like organising by year/month, etc.

**Comment by gregordr** [comment]
Do you mean internally, or over FTP/WebDAV?

**Comment by Backslashh** [comment]
oh I mean internally. 
So my current workflow is:
Phone upload to import directory > PhotoPrism grabs photos from import directory and uses exiftool to rename the photos and moves them to my photos folder sorted by year/month.

This way, I don't need to manually rename files and I can keep a clean photo directory structure.

**Comment by gregordr** [comment]
I understand now! So atm the internal storing of pictures is not meant for external consumption unfortunately. The files are all named according the unique IDs, so this won't be possible I'm afraid.
