### ISSUE TITLE
[Feature Request] Import directory

### ISSUE THREAD

**Issue by Backslashh** [gregordr/ImageStore#53]
Expose an import directory to ImageStore so that photos can be uploaded/dumped into this folder for ImageStore to index, sort and add to the backend filesystem.

**Comment by gregordr** [comment]
Would #52 solve this for you? If there was a WebDAV endpoint, you could open that as a directory and dump everything there?

**Comment by Backslashh** [comment]
Yep, that'd do it for sure.
That way ImageStore could watch that directory for changes and auto import
files within that folder. Having a configurable import delay on folder
change would be helpful too.

**Comment by gregordr** [comment]
Is a feature now :)
