### ISSUE TITLE
Build arm64 images

### ISSUE THREAD

**Issue by vaskozl** [gregordr/ImageStore#7]
Love the project and how the container images are segmented.

Would like to deploy on my k8s RPi cluster which is arm64 based. Currently there are only amd64 images on docker hub.

**Comment by darrylgibbs** [comment]
Second this!

**Comment by gregordr** [comment]
I have been trying to set up an action that does this - however, for some reason it keeps failing :/ If any of you know what is wrong, please let me know!

**Comment by lukasmoellerch** [comment]
The glibc version of the node base image seems to be outdated (https://github.com/lovell/sharp/issues/2482).

This PR could possibly fix the issue: https://github.com/lovell/sharp-libvips/pull/73

**Comment by gregordr** [comment]
I made some changes, let me know if it works for you now!

**Comment by gregordr** [comment]
Alright, I confirmed that everything works! 
Apparently, some devices require that a package is installed before things execute correctly:

arm/v7:
```
wget http://ftp.ch.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```
arm64:
```
wget http://ftp.ch.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_arm64.deb
sudo dpkg -i libseccomp2_2.5.1-1_arm64.deb

```

**Comment by vaskozl** [comment]
Sorry for the delay in testing,

Can confirm the images works great on arm64! :tada: 

I deployed on k8s with ingress-nginx and a replica count of two for the frontend/backend. Anybody interested in k8s deployment manifests:
https://github.com/vaskozl/home-infra/commit/5606a8eec1ec05c734d1892ca66d9fe802b02c29
