### ISSUE TITLE
Accessible from non-local networks

### ISSUE THREAD

**Issue by Ullarah** [gregordr/ImageStore#9]
There seems to be an issue with accessing the application with a domain name as it's trying to resolve the backend (port 4000).  I've had a quick look at the source and it mentions the PUBLIC_URL as a variable.  Hope I'm making sense so far.

https://github.com/gregordr/ImageStore/blob/main/frontend/src/API.tsx#L15

I can access the frontend with no issue, but because it's trying to connect to the backend on port 4000 and possible the db connection too it fails.  However it works just fine using the local address.  Not sure if it's a code issue or perhaps a docker configuration.

**Comment by gregordr** [comment]
It's not ideal, but it should usually be possible to host the backend on the corresponding port, shouldn't it? If not, I will probably have to add an nginx reverse proxy to the docker-compose, so that we can use one port for everything.

**Comment by gregordr** [comment]
Edit: I added an nginx reverse proxy - please let me know if your issue is fixed!

**Comment by Ullarah** [comment]
Not sure what's happened but now it can't be accessed from both local networks and external.  I wiped the VM and re-pulled the docker images.  Looking through the docker logs it seems everything is working however in the browser console I see the following:

```
xhr.js:177 GET http://192.168.0.234:4000/media/all  net::ERR_CONNECTION_REFUSED
xhr.js:177 GET http://192.168.0.234:4000/albums/all net::ERR_CONNECTION_REFUSED

createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.p.onerror (xhr.js:84)
```

**Comment by Ullarah** [comment]
Looks like it's the classic user error!  I forgot that I changed the postgresql password in the docker-compose.yml

It works great now! 👍

**Comment by gregordr** [comment]
Great :)
