### ISSUE TITLE
Use existing images

### ISSUE THREAD

**Issue by bigjimmy546** [gregordr/ImageStore#96]
Does ImageStore support existing images and folder structure? If so, where do I put or link existing images?
Thanks

**Comment by gregordr** [comment]
Hi, at the moment the folder structure is not supported, but you can check [the module](https://github.com/gregordr/ImageStore#list-of-modules) `import` which will create an import directory for you to put images into which will be processed.

**Comment by bigjimmy546** [comment]
Noted thank you
